/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSwimmersRouteImport } from './routes/api/swimmers'
import { Route as ApiRegistrationsRouteImport } from './routes/api/registrations'
import { Route as ApiRegisterRouteImport } from './routes/api/register'
import { Route as ApiPaymentsRouteImport } from './routes/api/payments'
import { Route as ApiPaymentRouteImport } from './routes/api/payment'
import { Route as ApiSwimmersIdRouteImport } from './routes/api/swimmers/$id'
import { Route as ApiAdminStatusRouteImport } from './routes/api/admin/status'

const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwimmersRoute = ApiSwimmersRouteImport.update({
  id: '/api/swimmers',
  path: '/api/swimmers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistrationsRoute = ApiRegistrationsRouteImport.update({
  id: '/api/registrations',
  path: '/api/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegisterRoute = ApiRegisterRouteImport.update({
  id: '/api/register',
  path: '/api/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsRoute = ApiPaymentsRouteImport.update({
  id: '/api/payments',
  path: '/api/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentRoute = ApiPaymentRouteImport.update({
  id: '/api/payment',
  path: '/api/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwimmersIdRoute = ApiSwimmersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSwimmersRoute,
} as any)
const ApiAdminStatusRoute = ApiAdminStatusRouteImport.update({
  id: '/api/admin/status',
  path: '/api/admin/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/parent': typeof ParentRoute
  '/api/payment': typeof ApiPaymentRoute
  '/api/payments': typeof ApiPaymentsRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/registrations': typeof ApiRegistrationsRoute
  '/api/swimmers': typeof ApiSwimmersRouteWithChildren
  '/api/admin/status': typeof ApiAdminStatusRoute
  '/api/swimmers/$id': typeof ApiSwimmersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/parent': typeof ParentRoute
  '/api/payment': typeof ApiPaymentRoute
  '/api/payments': typeof ApiPaymentsRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/registrations': typeof ApiRegistrationsRoute
  '/api/swimmers': typeof ApiSwimmersRouteWithChildren
  '/api/admin/status': typeof ApiAdminStatusRoute
  '/api/swimmers/$id': typeof ApiSwimmersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/parent': typeof ParentRoute
  '/api/payment': typeof ApiPaymentRoute
  '/api/payments': typeof ApiPaymentsRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/registrations': typeof ApiRegistrationsRoute
  '/api/swimmers': typeof ApiSwimmersRouteWithChildren
  '/api/admin/status': typeof ApiAdminStatusRoute
  '/api/swimmers/$id': typeof ApiSwimmersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/parent'
    | '/api/payment'
    | '/api/payments'
    | '/api/register'
    | '/api/registrations'
    | '/api/swimmers'
    | '/api/admin/status'
    | '/api/swimmers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/parent'
    | '/api/payment'
    | '/api/payments'
    | '/api/register'
    | '/api/registrations'
    | '/api/swimmers'
    | '/api/admin/status'
    | '/api/swimmers/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/parent'
    | '/api/payment'
    | '/api/payments'
    | '/api/register'
    | '/api/registrations'
    | '/api/swimmers'
    | '/api/admin/status'
    | '/api/swimmers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ParentRoute: typeof ParentRoute
  ApiPaymentRoute: typeof ApiPaymentRoute
  ApiPaymentsRoute: typeof ApiPaymentsRoute
  ApiRegisterRoute: typeof ApiRegisterRoute
  ApiRegistrationsRoute: typeof ApiRegistrationsRoute
  ApiSwimmersRoute: typeof ApiSwimmersRouteWithChildren
  ApiAdminStatusRoute: typeof ApiAdminStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swimmers': {
      id: '/api/swimmers'
      path: '/api/swimmers'
      fullPath: '/api/swimmers'
      preLoaderRoute: typeof ApiSwimmersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registrations': {
      id: '/api/registrations'
      path: '/api/registrations'
      fullPath: '/api/registrations'
      preLoaderRoute: typeof ApiRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/register': {
      id: '/api/register'
      path: '/api/register'
      fullPath: '/api/register'
      preLoaderRoute: typeof ApiRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments': {
      id: '/api/payments'
      path: '/api/payments'
      fullPath: '/api/payments'
      preLoaderRoute: typeof ApiPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment': {
      id: '/api/payment'
      path: '/api/payment'
      fullPath: '/api/payment'
      preLoaderRoute: typeof ApiPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swimmers/$id': {
      id: '/api/swimmers/$id'
      path: '/$id'
      fullPath: '/api/swimmers/$id'
      preLoaderRoute: typeof ApiSwimmersIdRouteImport
      parentRoute: typeof ApiSwimmersRoute
    }
    '/api/admin/status': {
      id: '/api/admin/status'
      path: '/api/admin/status'
      fullPath: '/api/admin/status'
      preLoaderRoute: typeof ApiAdminStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiSwimmersRouteChildren {
  ApiSwimmersIdRoute: typeof ApiSwimmersIdRoute
}

const ApiSwimmersRouteChildren: ApiSwimmersRouteChildren = {
  ApiSwimmersIdRoute: ApiSwimmersIdRoute,
}

const ApiSwimmersRouteWithChildren = ApiSwimmersRoute._addFileChildren(
  ApiSwimmersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ParentRoute: ParentRoute,
  ApiPaymentRoute: ApiPaymentRoute,
  ApiPaymentsRoute: ApiPaymentsRoute,
  ApiRegisterRoute: ApiRegisterRoute,
  ApiRegistrationsRoute: ApiRegistrationsRoute,
  ApiSwimmersRoute: ApiSwimmersRouteWithChildren,
  ApiAdminStatusRoute: ApiAdminStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
