/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as DormantRouteImport } from './routes/dormant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSwimmersRouteImport } from './routes/api/swimmers'
import { Route as ApiSwimmerParentsRouteImport } from './routes/api/swimmer-parents'
import { Route as ApiRosterStatusRouteImport } from './routes/api/roster-status'
import { Route as ApiRoadmapRouteImport } from './routes/api/roadmap'
import { Route as ApiRegistrationsRouteImport } from './routes/api/registrations'
import { Route as ApiRegisterRouteImport } from './routes/api/register'
import { Route as ApiPaymentsRouteImport } from './routes/api/payments'
import { Route as ApiPaymentRouteImport } from './routes/api/payment'
import { Route as ApiParentsRouteImport } from './routes/api/parents'
import { Route as ApiNotesRouteImport } from './routes/api/notes'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiTrackerSummaryRouteImport } from './routes/api/tracker/summary'
import { Route as ApiTrackerDataRouteImport } from './routes/api/tracker/data'
import { Route as ApiSwimmersIdRouteImport } from './routes/api/swimmers/$id'
import { Route as ApiRoadmapCommentRouteImport } from './routes/api/roadmap/comment'
import { Route as ApiParentsLinkRouteImport } from './routes/api/parents/link'
import { Route as ApiMeetDetailRouteImport } from './routes/api/meet/detail'
import { Route as ApiMeRegistrationRouteImport } from './routes/api/me/registration'
import { Route as ApiMeRegisterRouteImport } from './routes/api/me/register'
import { Route as ApiMePaymentRouteImport } from './routes/api/me/payment'
import { Route as ApiMeParentRouteImport } from './routes/api/me/parent'
import { Route as ApiMeLinkRouteImport } from './routes/api/me/link'
import { Route as ApiMeDataRouteImport } from './routes/api/me/data'
import { Route as ApiMeClaimableRouteImport } from './routes/api/me/claimable'
import { Route as ApiAuthVerifyCodeRouteImport } from './routes/api/auth/verify-code'
import { Route as ApiAuthRequestCodeRouteImport } from './routes/api/auth/request-code'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAthleteAssessmentRouteImport } from './routes/api/athlete/assessment'
import { Route as ApiAdminStatusRouteImport } from './routes/api/admin/status'
import { Route as ApiAdminParentImportRouteImport } from './routes/api/admin/parent-import'
import { Route as ApiAdminClaimsRouteImport } from './routes/api/admin/claims'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const DormantRoute = DormantRouteImport.update({
  id: '/dormant',
  path: '/dormant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwimmersRoute = ApiSwimmersRouteImport.update({
  id: '/api/swimmers',
  path: '/api/swimmers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwimmerParentsRoute = ApiSwimmerParentsRouteImport.update({
  id: '/api/swimmer-parents',
  path: '/api/swimmer-parents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRosterStatusRoute = ApiRosterStatusRouteImport.update({
  id: '/api/roster-status',
  path: '/api/roster-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoadmapRoute = ApiRoadmapRouteImport.update({
  id: '/api/roadmap',
  path: '/api/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistrationsRoute = ApiRegistrationsRouteImport.update({
  id: '/api/registrations',
  path: '/api/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegisterRoute = ApiRegisterRouteImport.update({
  id: '/api/register',
  path: '/api/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsRoute = ApiPaymentsRouteImport.update({
  id: '/api/payments',
  path: '/api/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentRoute = ApiPaymentRouteImport.update({
  id: '/api/payment',
  path: '/api/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParentsRoute = ApiParentsRouteImport.update({
  id: '/api/parents',
  path: '/api/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesRoute = ApiNotesRouteImport.update({
  id: '/api/notes',
  path: '/api/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackerSummaryRoute = ApiTrackerSummaryRouteImport.update({
  id: '/api/tracker/summary',
  path: '/api/tracker/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackerDataRoute = ApiTrackerDataRouteImport.update({
  id: '/api/tracker/data',
  path: '/api/tracker/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwimmersIdRoute = ApiSwimmersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSwimmersRoute,
} as any)
const ApiRoadmapCommentRoute = ApiRoadmapCommentRouteImport.update({
  id: '/comment',
  path: '/comment',
  getParentRoute: () => ApiRoadmapRoute,
} as any)
const ApiParentsLinkRoute = ApiParentsLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => ApiParentsRoute,
} as any)
const ApiMeetDetailRoute = ApiMeetDetailRouteImport.update({
  id: '/api/meet/detail',
  path: '/api/meet/detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRegistrationRoute = ApiMeRegistrationRouteImport.update({
  id: '/api/me/registration',
  path: '/api/me/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRegisterRoute = ApiMeRegisterRouteImport.update({
  id: '/api/me/register',
  path: '/api/me/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMePaymentRoute = ApiMePaymentRouteImport.update({
  id: '/api/me/payment',
  path: '/api/me/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeParentRoute = ApiMeParentRouteImport.update({
  id: '/api/me/parent',
  path: '/api/me/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeLinkRoute = ApiMeLinkRouteImport.update({
  id: '/api/me/link',
  path: '/api/me/link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeDataRoute = ApiMeDataRouteImport.update({
  id: '/api/me/data',
  path: '/api/me/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeClaimableRoute = ApiMeClaimableRouteImport.update({
  id: '/api/me/claimable',
  path: '/api/me/claimable',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyCodeRoute = ApiAuthVerifyCodeRouteImport.update({
  id: '/api/auth/verify-code',
  path: '/api/auth/verify-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRequestCodeRoute = ApiAuthRequestCodeRouteImport.update({
  id: '/api/auth/request-code',
  path: '/api/auth/request-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAthleteAssessmentRoute = ApiAthleteAssessmentRouteImport.update({
  id: '/api/athlete/assessment',
  path: '/api/athlete/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatusRoute = ApiAdminStatusRouteImport.update({
  id: '/api/admin/status',
  path: '/api/admin/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminParentImportRoute = ApiAdminParentImportRouteImport.update({
  id: '/api/admin/parent-import',
  path: '/api/admin/parent-import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminClaimsRoute = ApiAdminClaimsRouteImport.update({
  id: '/api/admin/claims',
  path: '/api/admin/claims',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dormant': typeof DormantRoute
  '/parent': typeof ParentRoute
  '/roadmap': typeof RoadmapRoute
  '/tracker': typeof TrackerRoute
  '/welcome': typeof WelcomeRoute
  '/api/health': typeof ApiHealthRoute
  '/api/notes': typeof ApiNotesRoute
  '/api/parents': typeof ApiParentsRouteWithChildren
  '/api/payment': typeof ApiPaymentRoute
  '/api/payments': typeof ApiPaymentsRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/registrations': typeof ApiRegistrationsRoute
  '/api/roadmap': typeof ApiRoadmapRouteWithChildren
  '/api/roster-status': typeof ApiRosterStatusRoute
  '/api/swimmer-parents': typeof ApiSwimmerParentsRoute
  '/api/swimmers': typeof ApiSwimmersRouteWithChildren
  '/api/admin/claims': typeof ApiAdminClaimsRoute
  '/api/admin/parent-import': typeof ApiAdminParentImportRoute
  '/api/admin/status': typeof ApiAdminStatusRoute
  '/api/athlete/assessment': typeof ApiAthleteAssessmentRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/request-code': typeof ApiAuthRequestCodeRoute
  '/api/auth/verify-code': typeof ApiAuthVerifyCodeRoute
  '/api/me/claimable': typeof ApiMeClaimableRoute
  '/api/me/data': typeof ApiMeDataRoute
  '/api/me/link': typeof ApiMeLinkRoute
  '/api/me/parent': typeof ApiMeParentRoute
  '/api/me/payment': typeof ApiMePaymentRoute
  '/api/me/register': typeof ApiMeRegisterRoute
  '/api/me/registration': typeof ApiMeRegistrationRoute
  '/api/meet/detail': typeof ApiMeetDetailRoute
  '/api/parents/link': typeof ApiParentsLinkRoute
  '/api/roadmap/comment': typeof ApiRoadmapCommentRoute
  '/api/swimmers/$id': typeof ApiSwimmersIdRoute
  '/api/tracker/data': typeof ApiTrackerDataRoute
  '/api/tracker/summary': typeof ApiTrackerSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dormant': typeof DormantRoute
  '/parent': typeof ParentRoute
  '/roadmap': typeof RoadmapRoute
  '/tracker': typeof TrackerRoute
  '/welcome': typeof WelcomeRoute
  '/api/health': typeof ApiHealthRoute
  '/api/notes': typeof ApiNotesRoute
  '/api/parents': typeof ApiParentsRouteWithChildren
  '/api/payment': typeof ApiPaymentRoute
  '/api/payments': typeof ApiPaymentsRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/registrations': typeof ApiRegistrationsRoute
  '/api/roadmap': typeof ApiRoadmapRouteWithChildren
  '/api/roster-status': typeof ApiRosterStatusRoute
  '/api/swimmer-parents': typeof ApiSwimmerParentsRoute
  '/api/swimmers': typeof ApiSwimmersRouteWithChildren
  '/api/admin/claims': typeof ApiAdminClaimsRoute
  '/api/admin/parent-import': typeof ApiAdminParentImportRoute
  '/api/admin/status': typeof ApiAdminStatusRoute
  '/api/athlete/assessment': typeof ApiAthleteAssessmentRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/request-code': typeof ApiAuthRequestCodeRoute
  '/api/auth/verify-code': typeof ApiAuthVerifyCodeRoute
  '/api/me/claimable': typeof ApiMeClaimableRoute
  '/api/me/data': typeof ApiMeDataRoute
  '/api/me/link': typeof ApiMeLinkRoute
  '/api/me/parent': typeof ApiMeParentRoute
  '/api/me/payment': typeof ApiMePaymentRoute
  '/api/me/register': typeof ApiMeRegisterRoute
  '/api/me/registration': typeof ApiMeRegistrationRoute
  '/api/meet/detail': typeof ApiMeetDetailRoute
  '/api/parents/link': typeof ApiParentsLinkRoute
  '/api/roadmap/comment': typeof ApiRoadmapCommentRoute
  '/api/swimmers/$id': typeof ApiSwimmersIdRoute
  '/api/tracker/data': typeof ApiTrackerDataRoute
  '/api/tracker/summary': typeof ApiTrackerSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dormant': typeof DormantRoute
  '/parent': typeof ParentRoute
  '/roadmap': typeof RoadmapRoute
  '/tracker': typeof TrackerRoute
  '/welcome': typeof WelcomeRoute
  '/api/health': typeof ApiHealthRoute
  '/api/notes': typeof ApiNotesRoute
  '/api/parents': typeof ApiParentsRouteWithChildren
  '/api/payment': typeof ApiPaymentRoute
  '/api/payments': typeof ApiPaymentsRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/registrations': typeof ApiRegistrationsRoute
  '/api/roadmap': typeof ApiRoadmapRouteWithChildren
  '/api/roster-status': typeof ApiRosterStatusRoute
  '/api/swimmer-parents': typeof ApiSwimmerParentsRoute
  '/api/swimmers': typeof ApiSwimmersRouteWithChildren
  '/api/admin/claims': typeof ApiAdminClaimsRoute
  '/api/admin/parent-import': typeof ApiAdminParentImportRoute
  '/api/admin/status': typeof ApiAdminStatusRoute
  '/api/athlete/assessment': typeof ApiAthleteAssessmentRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/request-code': typeof ApiAuthRequestCodeRoute
  '/api/auth/verify-code': typeof ApiAuthVerifyCodeRoute
  '/api/me/claimable': typeof ApiMeClaimableRoute
  '/api/me/data': typeof ApiMeDataRoute
  '/api/me/link': typeof ApiMeLinkRoute
  '/api/me/parent': typeof ApiMeParentRoute
  '/api/me/payment': typeof ApiMePaymentRoute
  '/api/me/register': typeof ApiMeRegisterRoute
  '/api/me/registration': typeof ApiMeRegistrationRoute
  '/api/meet/detail': typeof ApiMeetDetailRoute
  '/api/parents/link': typeof ApiParentsLinkRoute
  '/api/roadmap/comment': typeof ApiRoadmapCommentRoute
  '/api/swimmers/$id': typeof ApiSwimmersIdRoute
  '/api/tracker/data': typeof ApiTrackerDataRoute
  '/api/tracker/summary': typeof ApiTrackerSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dormant'
    | '/parent'
    | '/roadmap'
    | '/tracker'
    | '/welcome'
    | '/api/health'
    | '/api/notes'
    | '/api/parents'
    | '/api/payment'
    | '/api/payments'
    | '/api/register'
    | '/api/registrations'
    | '/api/roadmap'
    | '/api/roster-status'
    | '/api/swimmer-parents'
    | '/api/swimmers'
    | '/api/admin/claims'
    | '/api/admin/parent-import'
    | '/api/admin/status'
    | '/api/athlete/assessment'
    | '/api/auth/me'
    | '/api/auth/request-code'
    | '/api/auth/verify-code'
    | '/api/me/claimable'
    | '/api/me/data'
    | '/api/me/link'
    | '/api/me/parent'
    | '/api/me/payment'
    | '/api/me/register'
    | '/api/me/registration'
    | '/api/meet/detail'
    | '/api/parents/link'
    | '/api/roadmap/comment'
    | '/api/swimmers/$id'
    | '/api/tracker/data'
    | '/api/tracker/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dormant'
    | '/parent'
    | '/roadmap'
    | '/tracker'
    | '/welcome'
    | '/api/health'
    | '/api/notes'
    | '/api/parents'
    | '/api/payment'
    | '/api/payments'
    | '/api/register'
    | '/api/registrations'
    | '/api/roadmap'
    | '/api/roster-status'
    | '/api/swimmer-parents'
    | '/api/swimmers'
    | '/api/admin/claims'
    | '/api/admin/parent-import'
    | '/api/admin/status'
    | '/api/athlete/assessment'
    | '/api/auth/me'
    | '/api/auth/request-code'
    | '/api/auth/verify-code'
    | '/api/me/claimable'
    | '/api/me/data'
    | '/api/me/link'
    | '/api/me/parent'
    | '/api/me/payment'
    | '/api/me/register'
    | '/api/me/registration'
    | '/api/meet/detail'
    | '/api/parents/link'
    | '/api/roadmap/comment'
    | '/api/swimmers/$id'
    | '/api/tracker/data'
    | '/api/tracker/summary'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dormant'
    | '/parent'
    | '/roadmap'
    | '/tracker'
    | '/welcome'
    | '/api/health'
    | '/api/notes'
    | '/api/parents'
    | '/api/payment'
    | '/api/payments'
    | '/api/register'
    | '/api/registrations'
    | '/api/roadmap'
    | '/api/roster-status'
    | '/api/swimmer-parents'
    | '/api/swimmers'
    | '/api/admin/claims'
    | '/api/admin/parent-import'
    | '/api/admin/status'
    | '/api/athlete/assessment'
    | '/api/auth/me'
    | '/api/auth/request-code'
    | '/api/auth/verify-code'
    | '/api/me/claimable'
    | '/api/me/data'
    | '/api/me/link'
    | '/api/me/parent'
    | '/api/me/payment'
    | '/api/me/register'
    | '/api/me/registration'
    | '/api/meet/detail'
    | '/api/parents/link'
    | '/api/roadmap/comment'
    | '/api/swimmers/$id'
    | '/api/tracker/data'
    | '/api/tracker/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DormantRoute: typeof DormantRoute
  ParentRoute: typeof ParentRoute
  RoadmapRoute: typeof RoadmapRoute
  TrackerRoute: typeof TrackerRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiNotesRoute: typeof ApiNotesRoute
  ApiParentsRoute: typeof ApiParentsRouteWithChildren
  ApiPaymentRoute: typeof ApiPaymentRoute
  ApiPaymentsRoute: typeof ApiPaymentsRoute
  ApiRegisterRoute: typeof ApiRegisterRoute
  ApiRegistrationsRoute: typeof ApiRegistrationsRoute
  ApiRoadmapRoute: typeof ApiRoadmapRouteWithChildren
  ApiRosterStatusRoute: typeof ApiRosterStatusRoute
  ApiSwimmerParentsRoute: typeof ApiSwimmerParentsRoute
  ApiSwimmersRoute: typeof ApiSwimmersRouteWithChildren
  ApiAdminClaimsRoute: typeof ApiAdminClaimsRoute
  ApiAdminParentImportRoute: typeof ApiAdminParentImportRoute
  ApiAdminStatusRoute: typeof ApiAdminStatusRoute
  ApiAthleteAssessmentRoute: typeof ApiAthleteAssessmentRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRequestCodeRoute: typeof ApiAuthRequestCodeRoute
  ApiAuthVerifyCodeRoute: typeof ApiAuthVerifyCodeRoute
  ApiMeClaimableRoute: typeof ApiMeClaimableRoute
  ApiMeDataRoute: typeof ApiMeDataRoute
  ApiMeLinkRoute: typeof ApiMeLinkRoute
  ApiMeParentRoute: typeof ApiMeParentRoute
  ApiMePaymentRoute: typeof ApiMePaymentRoute
  ApiMeRegisterRoute: typeof ApiMeRegisterRoute
  ApiMeRegistrationRoute: typeof ApiMeRegistrationRoute
  ApiMeetDetailRoute: typeof ApiMeetDetailRoute
  ApiTrackerDataRoute: typeof ApiTrackerDataRoute
  ApiTrackerSummaryRoute: typeof ApiTrackerSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dormant': {
      id: '/dormant'
      path: '/dormant'
      fullPath: '/dormant'
      preLoaderRoute: typeof DormantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swimmers': {
      id: '/api/swimmers'
      path: '/api/swimmers'
      fullPath: '/api/swimmers'
      preLoaderRoute: typeof ApiSwimmersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swimmer-parents': {
      id: '/api/swimmer-parents'
      path: '/api/swimmer-parents'
      fullPath: '/api/swimmer-parents'
      preLoaderRoute: typeof ApiSwimmerParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roster-status': {
      id: '/api/roster-status'
      path: '/api/roster-status'
      fullPath: '/api/roster-status'
      preLoaderRoute: typeof ApiRosterStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roadmap': {
      id: '/api/roadmap'
      path: '/api/roadmap'
      fullPath: '/api/roadmap'
      preLoaderRoute: typeof ApiRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registrations': {
      id: '/api/registrations'
      path: '/api/registrations'
      fullPath: '/api/registrations'
      preLoaderRoute: typeof ApiRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/register': {
      id: '/api/register'
      path: '/api/register'
      fullPath: '/api/register'
      preLoaderRoute: typeof ApiRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments': {
      id: '/api/payments'
      path: '/api/payments'
      fullPath: '/api/payments'
      preLoaderRoute: typeof ApiPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment': {
      id: '/api/payment'
      path: '/api/payment'
      fullPath: '/api/payment'
      preLoaderRoute: typeof ApiPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parents': {
      id: '/api/parents'
      path: '/api/parents'
      fullPath: '/api/parents'
      preLoaderRoute: typeof ApiParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes': {
      id: '/api/notes'
      path: '/api/notes'
      fullPath: '/api/notes'
      preLoaderRoute: typeof ApiNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tracker/summary': {
      id: '/api/tracker/summary'
      path: '/api/tracker/summary'
      fullPath: '/api/tracker/summary'
      preLoaderRoute: typeof ApiTrackerSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tracker/data': {
      id: '/api/tracker/data'
      path: '/api/tracker/data'
      fullPath: '/api/tracker/data'
      preLoaderRoute: typeof ApiTrackerDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swimmers/$id': {
      id: '/api/swimmers/$id'
      path: '/$id'
      fullPath: '/api/swimmers/$id'
      preLoaderRoute: typeof ApiSwimmersIdRouteImport
      parentRoute: typeof ApiSwimmersRoute
    }
    '/api/roadmap/comment': {
      id: '/api/roadmap/comment'
      path: '/comment'
      fullPath: '/api/roadmap/comment'
      preLoaderRoute: typeof ApiRoadmapCommentRouteImport
      parentRoute: typeof ApiRoadmapRoute
    }
    '/api/parents/link': {
      id: '/api/parents/link'
      path: '/link'
      fullPath: '/api/parents/link'
      preLoaderRoute: typeof ApiParentsLinkRouteImport
      parentRoute: typeof ApiParentsRoute
    }
    '/api/meet/detail': {
      id: '/api/meet/detail'
      path: '/api/meet/detail'
      fullPath: '/api/meet/detail'
      preLoaderRoute: typeof ApiMeetDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/registration': {
      id: '/api/me/registration'
      path: '/api/me/registration'
      fullPath: '/api/me/registration'
      preLoaderRoute: typeof ApiMeRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/register': {
      id: '/api/me/register'
      path: '/api/me/register'
      fullPath: '/api/me/register'
      preLoaderRoute: typeof ApiMeRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/payment': {
      id: '/api/me/payment'
      path: '/api/me/payment'
      fullPath: '/api/me/payment'
      preLoaderRoute: typeof ApiMePaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/parent': {
      id: '/api/me/parent'
      path: '/api/me/parent'
      fullPath: '/api/me/parent'
      preLoaderRoute: typeof ApiMeParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/link': {
      id: '/api/me/link'
      path: '/api/me/link'
      fullPath: '/api/me/link'
      preLoaderRoute: typeof ApiMeLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/data': {
      id: '/api/me/data'
      path: '/api/me/data'
      fullPath: '/api/me/data'
      preLoaderRoute: typeof ApiMeDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/claimable': {
      id: '/api/me/claimable'
      path: '/api/me/claimable'
      fullPath: '/api/me/claimable'
      preLoaderRoute: typeof ApiMeClaimableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify-code': {
      id: '/api/auth/verify-code'
      path: '/api/auth/verify-code'
      fullPath: '/api/auth/verify-code'
      preLoaderRoute: typeof ApiAuthVerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/request-code': {
      id: '/api/auth/request-code'
      path: '/api/auth/request-code'
      fullPath: '/api/auth/request-code'
      preLoaderRoute: typeof ApiAuthRequestCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/athlete/assessment': {
      id: '/api/athlete/assessment'
      path: '/api/athlete/assessment'
      fullPath: '/api/athlete/assessment'
      preLoaderRoute: typeof ApiAthleteAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/status': {
      id: '/api/admin/status'
      path: '/api/admin/status'
      fullPath: '/api/admin/status'
      preLoaderRoute: typeof ApiAdminStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/parent-import': {
      id: '/api/admin/parent-import'
      path: '/api/admin/parent-import'
      fullPath: '/api/admin/parent-import'
      preLoaderRoute: typeof ApiAdminParentImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/claims': {
      id: '/api/admin/claims'
      path: '/api/admin/claims'
      fullPath: '/api/admin/claims'
      preLoaderRoute: typeof ApiAdminClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiParentsRouteChildren {
  ApiParentsLinkRoute: typeof ApiParentsLinkRoute
}

const ApiParentsRouteChildren: ApiParentsRouteChildren = {
  ApiParentsLinkRoute: ApiParentsLinkRoute,
}

const ApiParentsRouteWithChildren = ApiParentsRoute._addFileChildren(
  ApiParentsRouteChildren,
)

interface ApiRoadmapRouteChildren {
  ApiRoadmapCommentRoute: typeof ApiRoadmapCommentRoute
}

const ApiRoadmapRouteChildren: ApiRoadmapRouteChildren = {
  ApiRoadmapCommentRoute: ApiRoadmapCommentRoute,
}

const ApiRoadmapRouteWithChildren = ApiRoadmapRoute._addFileChildren(
  ApiRoadmapRouteChildren,
)

interface ApiSwimmersRouteChildren {
  ApiSwimmersIdRoute: typeof ApiSwimmersIdRoute
}

const ApiSwimmersRouteChildren: ApiSwimmersRouteChildren = {
  ApiSwimmersIdRoute: ApiSwimmersIdRoute,
}

const ApiSwimmersRouteWithChildren = ApiSwimmersRoute._addFileChildren(
  ApiSwimmersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DormantRoute: DormantRoute,
  ParentRoute: ParentRoute,
  RoadmapRoute: RoadmapRoute,
  TrackerRoute: TrackerRoute,
  WelcomeRoute: WelcomeRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiNotesRoute: ApiNotesRoute,
  ApiParentsRoute: ApiParentsRouteWithChildren,
  ApiPaymentRoute: ApiPaymentRoute,
  ApiPaymentsRoute: ApiPaymentsRoute,
  ApiRegisterRoute: ApiRegisterRoute,
  ApiRegistrationsRoute: ApiRegistrationsRoute,
  ApiRoadmapRoute: ApiRoadmapRouteWithChildren,
  ApiRosterStatusRoute: ApiRosterStatusRoute,
  ApiSwimmerParentsRoute: ApiSwimmerParentsRoute,
  ApiSwimmersRoute: ApiSwimmersRouteWithChildren,
  ApiAdminClaimsRoute: ApiAdminClaimsRoute,
  ApiAdminParentImportRoute: ApiAdminParentImportRoute,
  ApiAdminStatusRoute: ApiAdminStatusRoute,
  ApiAthleteAssessmentRoute: ApiAthleteAssessmentRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRequestCodeRoute: ApiAuthRequestCodeRoute,
  ApiAuthVerifyCodeRoute: ApiAuthVerifyCodeRoute,
  ApiMeClaimableRoute: ApiMeClaimableRoute,
  ApiMeDataRoute: ApiMeDataRoute,
  ApiMeLinkRoute: ApiMeLinkRoute,
  ApiMeParentRoute: ApiMeParentRoute,
  ApiMePaymentRoute: ApiMePaymentRoute,
  ApiMeRegisterRoute: ApiMeRegisterRoute,
  ApiMeRegistrationRoute: ApiMeRegistrationRoute,
  ApiMeetDetailRoute: ApiMeetDetailRoute,
  ApiTrackerDataRoute: ApiTrackerDataRoute,
  ApiTrackerSummaryRoute: ApiTrackerSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
